Repository perlin-network/wavelet, pull requests merged in 2019-10, with the labels that each got.

#261 Speed up CollapseTransactions() by buffering changes to a map.
  cmd/wavelet/main.go
  collapse.go
  collapse_test.go
  contract.go
  contract_test.go
  tx_applier.go
  tx_applier_test.go
Labels: enhancement

#224 Some micro optimizations in db.go and node.go
  avl/node.go
  avl/node_test.go
  db.go
  db_test.go
Labels: enhancement

#241 Increase test coverage.
  .codecov.yml
  conf/conf.go
  conf/conf_test.go
  ledger.go
  lru/lru_test.go
  tx_applier_test.go
  tx_json_test.go
  utils.go
  utils_test.go
Labels: enhancement

#244 Cleanup ledger.
  accounts.go
  api/mod.go
  cmd/wavelet/cli.go
  cmd/wavelet/main.go
  cmd/wavelet/main_test.go
  ledger.go
  log/mod.go
  recovery.go
  testutil.go
Labels: enhancement

#283 Send list of tx id instead of bloom filter for pulling transactions
  ledger.go
  mempool.go
  protocol.go
  rpc.pb.go
  rpc.proto
Labels: enhancement

#284 Improve Windows Support
  cmd/wavelet/main.go
  cmd/wavelet/update.go
  cmd/wavelet/update_unix.go
  cmd/wavelet/update_windows.go
  recovery_unix.go
  scripts/helper.sh
  sys/version.go
Labels: bug

#285 Minor fix for a panic on failed pulls
  ledger.go
Labels: bug

#287 Cleaned up locking for Transactions
  api/mod.go
  ledger.go
  protocol.go
  transactions.go
Labels: enhancement

#286 Nonce checking and support.
  api/mod.go
  api/msg.go
  cmd/benchmark/build.go
  cmd/benchmark/flood.go
  cmd/benchmark/main.go
  cmd/benchmark/net.go
  cmd/benchmark/node.go
  cmd/wavelet/actions.go
  ledger.go
  metrics.go
  protocol.go
  transactions.go
  tx.go
  wctl/client.go
  wctl/msg.go
Labels: enhancement

#288 Remove mempool, and cleanup locks around transactions with helper methods.
  api/mod.go
  cmd/wavelet/actions.go
  ledger.go
  mempool.go
  transactions.go
Labels: enhancement

#289 Fix NewTransaction() test errors.
  tx_test.go
Labels: bug

#290 Mark missing transactions.
  transactions.go
Labels: enhancement

#291 Have missing transaction IDs expire over time.
  ledger.go
  transactions.go
Labels: enhancement

#293 Create fuzzing tests, off-by-one error tests, and edge case tests for the Transactions module to achieve 100% code coverage.
  ledger.go
  protocol.go
  transactions.go
  transactions_test.go
Labels: enhancement

#222 Separate cmd/wavelet into a daemon and HTTP CLI interface.
  .travis.yml
  api/mod.go
  api/mod_test.go
  api/msg.go
  cmd/benchmark/flood.go
  cmd/benchmark/main.go
  cmd/wavelet/actions.go
  cmd/wavelet/cli.go
  cmd/wavelet/completion.go
  cmd/wavelet/events.go
  cmd/wavelet/main.go
  cmd/wavelet/main_test.go
  cmd/wavelet/node/node.go
  cmd/wavelet/update.go
  cmd/wctl/main.go
  go.mod
  go.sum
  ledger.go
  scripts/helper.sh
  site/docs/api.md
  sys/version.go
  transactions.go
  wctl/account.go
  wctl/batch.go
  wctl/client.go
  wctl/error.go
  wctl/helper.go
  wctl/id.go
  wctl/ledger.go
  wctl/msg.go
  wctl/node.go
  wctl/nonce.go
  wctl/tx.go
  wctl/tx_batch.go
  wctl/tx_call.go
  wctl/tx_deposit.go
  wctl/tx_find.go
  wctl/tx_pay.go
  wctl/tx_spawn.go
  wctl/tx_stake.go
  wctl/wctl.go
  wctl/ws.go
  wctl/ws_accounts.go
  wctl/ws_callbacks.go
  wctl/ws_consensus.go
  wctl/ws_contract.go
  wctl/ws_metrics.go
  wctl/ws_network.go
  wctl/ws_stake.go
  wctl/ws_tx.go
Labels: enhancement

#297 Add more debug info into cmd/wavelet, and make what transactions are proposed into a block more strict.
  api/msg.go
  cmd/wavelet/actions.go
  transactions.go
  wctl/ledger.go
Labels: enhancement

#299 Minor cleanup over transactions, and fix off-by-one error in wctl.
  transactions.go
  tx.go
  wctl/tx.go
Labels: enhancement

#300 Logging fixes.
  cmd/wavelet/cli.go
  cmd/wavelet/events.go
  ledger.go
Labels: enhancement

#303 Add num_missing_tx, and have MarkMissing be an atomic CAS operation.
  api/msg.go
  cmd/wavelet/actions.go
  ledger.go
  transactions.go
  transactions_test.go
  wctl/ledger.go
Labels: bug, enhancement

#304 Refactor Snowball and add unit tests
  snowball.go
  snowball_test.go
  vote.go
Labels: enhancement

#306 Improve Snowball liveness by factoring and weighing in nil votes.
  .github/workflows/workflow.yml
  snowball.go
  transactions_test.go
  vote.go
  vote_test.go
Labels: enhancement

#310 Fix metrics for synced transactions.
  ledger.go
Labels: bug

#305 Ensure that callbacks are registered before listening
  api/mod.go
  cmd/wavelet/node/node.go
Labels: bug

#312 Change block id to consist of transaction ids.
  block.go
  conf/conf_test.go
  ledger.go
Labels: bug

#313 Fix Transaction Tag
  sys/const.go
Labels: bug
