Repository perlin-network/wavelet, pull requests merged in 2019-11, with the labels that each got.

#320 Update noise to latest.
  go.mod
  go.sum
Labels: enhancement

#327 WCTL: Fix Find method returned a Transaction when the ID is actually a Contract
  wctl/tx_find.go
Labels: bug

#328 WCTL: fix pay to contract where the contract parameters are not set.
  wctl/tx_pay.go
Labels: bug

#330 Use cuckoo filter instead of bloomfilter.
  conf/conf.go
  go.mod
  go.sum
  ledger.go
  ledger_test.go
  protocol.go
  transactions.go
  transactions_test.go
Labels: enhancement

#346 Add abstract worker pool.
  cmd/wavelet/node/node.go
  conf/conf.go
  genesis.go
  genesis_test.go
  ledger.go
  recovery.go
  testutil.go
  worker_pool.go
  worker_pool_test.go
Labels: quality improvements

#350 Fix Ledger Status API response
  api/msg.go
Labels: bug

#332 Test all packages
  .github/workflows/workflow.yml
  api/mod.go
  api/mod_integration_test.go
  api/mod_ws_integration_test.go
  api/msg_test.go
  api/ratelimiter.go
  api/ratelimiter_test.go
  api/ws.go
  api/ws_test.go
  avl/node_test.go
  avl/tree_test.go
  cmd/wavelet/actions.go
  cmd/wavelet/events.go
  cmd/wavelet/main.go
  cmd/wavelet/main_integration_test.go
  conf/conf_test.go
  db_test.go
  debounce/debounce_test.go
  genesis.go
  genesis_integration_test.go
  ledger.go
  ledger_integration_test.go
  log/mod.go
  lru/lru_test.go
  snowball_test.go
  store/badger_test.go
  store/inmem_test.go
  store/leveldb_test.go
  testutil.go
  transactions_test.go
  tx_applier_test.go
  tx_json_test.go
  tx_payload_test.go
  tx_test.go
  utils_test.go
  vote_test.go
  worker_pool_test.go
Labels: bug, quality improvements

#354 Merge coverage result from multiple test runs
  .github/workflows/workflow.yml
Labels: bug

#367 Add optional signature verification on transaction add.
  api/mod.go
  api/mod_integration_test.go
  ledger.go
  testutil.go
  transactions.go
  transactions_test.go
Labels: enhancement

#366 Enalbe wsl and lll linters.
  .golangci.yml
  accounts.go
  api/cors.go
  api/middleware.go
  api/mod.go
  api/msg.go
  api/ws.go
  avl/node.go
  avl/queue.go
  avl/tree.go
  benchmarks/main.go
  block.go
  buffer.go
  cmd/benchmark/flood.go
  cmd/benchmark/main.go
  cmd/wavelet/actions.go
  cmd/wavelet/completion.go
  cmd/wavelet/events.go
  cmd/wavelet/main.go
  cmd/wavelet/node/node.go
  collapse.go
  collapse_test.go
  common.go
  contract.go
  db.go
  debounce/debounce.go
  genesis.go
  index.go
  ledger.go
  log/console.go
  log/io.go
  lru/lru.go
  protocol.go
  store/badger.go
  store/inmem.go
  store/leveldb.go
  store/testutil.go
  transactions.go
  tx.go
  tx_applier.go
  tx_json.go
  tx_payload.go
  utils.go
  vote.go
  wctl/error.go
  wctl/helper.go
  wctl/ledger.go
  wctl/msg.go
  wctl/node.go
  wctl/nonce.go
  wctl/tx.go
  wctl/tx_call.go
  wctl/wctl.go
  wctl/ws.go
  wctl/ws_accounts.go
  wctl/ws_consensus.go
  wctl/ws_contract.go
  wctl/ws_network.go
  wctl/ws_stake.go
  worker_pool.go
Labels: quality improvements

#372 Removed spurious output
  transactions.go
Labels: bug

#374 Fixed extraneous import
  transactions.go
Labels: bug

#375 Continue to use LevelDB until BadgerDB is sorted out
  cmd/wavelet/node/node.go
  testutil.go
Labels: bug

#373 Consolidate integration tests and cleanup
  .github/workflows/workflow.yml
  .gitignore
  Makefile
Labels: quality improvements
