Repository perlin-network/wavelet, pull requests merged in 2019-09, with the labels that each got.

#195 Keep example updated: change result type
  site/docs/examples/decentralized-todo-app.md
Labels: docs

#202 Optimize saving memory of contract snapshot.
  common.go
  contract.go
Labels: enhancement

#203 docs: fixed a compilation error in the code snippet
  site/docs/smart-contracts.md
Labels: docs

#142 Add tests for ledger
  ledger_test.go
  testutil.go
Labels: enhancement

#210 Improve Docker build support within the Makefile.
  Makefile
Labels: devops

#213 Make the computation of a rounds difficulty factor more robust to attacks by adversaries, and reduce round binary size.
  api/msg.go
  contract_test.go
  ledger.go
  ledger_test.go
  round.go
  tx_applier_test.go
Labels: bug, enhancement

#237 Fix failing tests
  ledger_test.go
  testutil.go
Labels: bug
