Repository perlin-network/wavelet, pull requests merged in 2019-08, with the labels that each got.

#150 Improve nops broadcasting.
  accounts.go
  api/mod_test.go
  api/mod_ws_test.go
  cmd/graph/main.go
  cmd/wavelet/main.go
  ledger.go
  ledger_test.go
  testutil.go
  utils_test.go
Labels: bug, enhancement

#148 Add transaction syncing.
  graph.go
  ledger.go
  protocol.go
  rpc.pb.go
  rpc.proto
  sys/const.go
Labels: enhancement

#119 docs: add API and WebSocket docs
  site/docs/api.md
  site/docs/ws.md
Labels: docs

#163 docs: add link to AssemblyScript smart contract SDK to index page
  site/website/pages/en/index.js
Labels: docs

#164 Fixed /accounts not plural.
  site/docs/api.md
Labels: docs

#159 Contract-related caching optimizations.
  avl/lru.go
  avl/tree.go
  contract.go
  contract_test.go
  ledger.go
  lru/lru.go
  lru/lru_test.go
  protocol.go
Labels: enhancement

#166 Ensure transaction collapsing only happens once for each round.
  ledger.go
  lru/lru.go
Labels: enhancement

#165 Add per-round caching for smart contract state.
  collapse.go
  contract.go
  contract_test.go
  tx_applier.go
  tx_applier_test.go
Labels: enhancement

#172 Added Docusaurus into CI.
  .travis.yml
Labels: docs

#178 fix: update example contract docs
  site/docs/smart-contracts.md
Labels: docs

#173 site: add command to set nightly as default channel
  site/docs/smart-contracts.md
Labels: docs

#168 docs: add markdown for tutorials on building decentralised applications on Wavelet
  site/docs/examples/decentralized-chat-app.md
  site/docs/examples/decentralized-todo-app.md
  site/website/sidebars.json
Labels: docs

#176 Fix logging in collapse transaction.
  ledger.go
Labels: bug

#167 Use highway hash instead of md5 for avl tree node id.
  api/mod_test.go
  avl/node.go
  go.mod
  go.sum
  ledger_test.go
  testutil.go
Labels: enhancement

#146 cmd/wavelet: fix unspecified flag not generating random wallet
  cmd/wavelet/cli.go
  cmd/wavelet/main.go
  cmd/wavelet/main_test.go
  go.mod
  go.sum
  testutil.go
Labels: enhancement

#134 State and transaction syncing - fixes and flow change.
  Makefile
  cmd/wavelet/actions.go
  cmd/wavelet/main_test.go
  collapse.go
  go.mod
  graph.go
  graph_test.go
  ledger.go
  ledger_test.go
  protocol.go
  round.go
  rpc.pb.go
  rpc.proto
  snowball.go
  snowball_test.go
  sys/const.go
  testdata/dummy.wasm
  testdata/invoke.wasm
  testutil.go
  vote.go
  vote_test.go
Labels: bug, enhancement

#179 docs: add chinese whitepaper to static
  site/website/static/whitepaper_cn.pdf
Labels: docs

#186 resolver: write heap pprof to disk upon oom
  recovery.go
Labels: bug, enhancement

#187 Apply contracts to vm in same order as they came in.
  collapse.go
  ledger.go
  ledger_test.go
  recovery.go
  testutil.go
  tx_applier.go
Labels: bug

#192 Fix memory leak in autocompletion trie.
  graph.go
Labels: bug

#194 Reduce memory allocations in contract VM caching, increase max number of memory pages per contract, and temporarily remove consensus invariant checks in the stall detector.
  collapse.go
  contract.go
  ledger.go
  recovery.go
  sys/const.go
  tx_applier.go
  tx_applier_test.go
Labels: bug, enhancement
