Repository perlin-network/wavelet, pull requests merged in 2019-07, with the labels that each got.

#116 Add JSON payload file support for send_transaction wctl command.
  api/mod.go
  api/mod_ws_test.go
  api/msg.go
  cmd/benchmark/flood.go
  cmd/wavelet/shell.go
  cmd/wctl/main.go
  cmd/wctl/payloads.md
  contract.go
  go.mod
  go.sum
  graph.go
  log.go
  sys/const.go
  testdata/amount_recipient_only.json
  testdata/contract_call.json
  testdata/contract_call.rs
  tx.go
  tx_applier.go
  tx_json.go
  tx_json_test.go
  tx_parser.go
Labels: enhancement

#124 Fix a minor bug in cmd/graph flag arguments.
  cmd/graph/main.go
Labels: bug

#123 Fix logged event type for rejected transactions.
  ledger.go
Labels: bug

#128 Fix committing an AVL tree with a nil root.
  avl/tree.go
  avl/tree_test.go
Labels: bug

#130 Fix debounce limiter timer related test.
  debounce/debounce_test.go
Labels: bug

#125 Ledger state syncing / pull missing transactions - minor cleanup and improvements.
  gossip.go
  ledger.go
  snowball.go
  sys/const.go
  utils.go
  vote.go
Labels: enhancement

#132 Prefer values over heap-allocated values, simplify memory model, and fix appending parent transaction seeds to transactions.
  api/mod.go
  cmd/wavelet/shell.go
  collapse.go
  genesis.go
  gossip.go
  graph.go
  graph_test.go
  ledger.go
  round.go
  rounds_test.go
  snowball.go
  sys/const.go
  tx.go
  tx_applier_test.go
  tx_json_test.go
Labels: bug, enhancement

#133 Crowdsourced gas fees for smart contracts.
  api/mod_test.go
  cmd/wavelet/shell.go
  cmd/wctl/payloads.md
  contract.go
  db.go
  site/docs/smart-contracts.md
  site/docs/transactions.md
  testdata/recursive_invocation.wasm
  testdata/transfer_back.wasm
  tx_applier.go
  tx_applier_test.go
  tx_json.go
  tx_parser.go
Labels: enhancement

#135 Validate WASM code for smart contracts before writing it into account state.
  .codecov.yml
  .travis.yml
  collapse.go
  contract.go
  go.mod
  go.sum
  index.go
  testdata/contract_call.rs
  tx_applier.go
  tx_json.go
Labels: docs, enhancement

#138 tx_parser: add tests
  tx_parser_test.go
Labels: enhancement

#137 utils: add test for SelectPeers
  avl/tree_test.go
  store/testutil.go
  utils_test.go
Labels: enhancement

#141 utils: fix failing TestSelectPeers
  store/inmem.go
  utils_test.go
Labels: bug

#139 tx_parser, tx_applier: refactor payload marshaling
  cmd/benchmark/flood.go
  cmd/graph/main.go
  cmd/wavelet/shell.go
  tx.go
  tx_applier.go
  tx_applier_test.go
  tx_parser.go
  tx_payload.go
  tx_payload_test.go
Labels: enhancement

#145 Call the start function of a smart contract (if exists) at initialization.
  contract.go
Labels: bug
