Repository perlin-network/wavelet, pull requests merged in 2019-12, with the labels that each got.

#380 Remove account nonce.
  api/mod.go
  api/mod_integration_test.go
  api/mod_ws_integration_test.go
  api/msg.go
  cmd/wavelet/actions.go
  collapse.go
  collapse_test.go
  db.go
  genesis.go
  genesis_integration_test.go
  ledger.go
  testutil.go
  wctl/account.go
  wctl/ledger.go
  wctl/nonce.go
  wctl/tx.go
  wctl/tx_find.go
  wctl/wctl.go
  wctl/ws_accounts.go
Labels: enhancement

#383 Fix build tags used to separate tests.
  api/mod_ws_integration_test.go
  api/msg_test.go
  api/ratelimiter_test.go
  api/ws_test.go
  avl/node_test.go
  avl/tree_test.go
  cmd/wavelet/main_integration_test.go
  conf/conf_test.go
  db_test.go
  debounce/debounce_test.go
  ledger_integration_test.go
  lru/lru_test.go
  snowball_test.go
  store/badger_test.go
  store/inmem_test.go
  store/leveldb_test.go
  transactions_test.go
  tx_applier_test.go
  tx_json_test.go
  tx_payload_test.go
  tx_test.go
  utils_test.go
  vote_test.go
  worker_pool_test.go
Labels: enhancement

#377 Test improvements and experiments.
  accounts_test.go
  ledger_integration_test.go
Labels: quality improvements

#376 State/transaction update logging optimizations.
  api/mod_ws_integration_test.go
  collapse.go
  genesis_integration_test.go
  ledger.go
  log.go
  log/io.go
  log/mod.go
  log_test.go
  snowball_test.go
  vote_test.go
Labels: enhancement

#384 Improve signature verification
  api/mod.go
  ledger.go
  transactions.go
  tx.go
Labels: enhancement

#388 Fix flaky debounce tests.
  debounce/debounce_test.go
Labels: enhancement

#391 Move workerpool to `internal`, and simplify vote normalization.
  internal/worker/pool.go
  internal/worker/pool_test.go
  ledger.go
  vote.go
  worker_pool.go
Labels: enhancement

#396 Separate usage of the "api.host" flag
  cmd/wavelet/main.go
Labels: enhancement

#385 Fix Dockerfile
  Dockerfile
Labels: bug

#399 Optimize cuckoo filter, and remove redundant config parameters.
  cmd/wavelet/actions.go
  cmd/wavelet/cli.go
  cmd/wavelet/main_integration_test.go
  conf/conf.go
  go.mod
  go.sum
  internal/cuckoo/filter.go
  internal/cuckoo/filter_test.go
  ledger.go
  ledger_integration_test.go
  protocol.go
Labels: enhancement

#387 Store transactions to db along with stored blocks.
  blocks.go
  cmd/wavelet/main_integration_test.go
  conf/conf.go
  db.go
  db_test.go
  ledger.go
  ledger_integration_test.go
  store/badger.go
  store/badger_test.go
  store/inmem.go
  store/leveldb.go
  store/leveldb_test.go
  store/mod.go
  testutil.go
  transactions.go
Labels: enhancement

#400 Have NewLedger return errors.
  api/mod_integration_test.go
  api/mod_ws_integration_test.go
  cmd/wavelet/node/node.go
  ledger.go
  testutil.go
  utils_test.go
Labels: bug

#403 Remove stake logger.
  api/mod.go
  api/mod_ws_integration_test.go
  cmd/wavelet/events.go
  log/mod.go
  site/docs/examples/decentralized-todo-app.md
  site/docs/examples/wasm-to-distributed-program.md
  site/docs/ws.md
  site/website/pages/en/index.js
  site/website/siteConfig.js
  wctl/wctl.go
  wctl/ws.go
  wctl/ws_callbacks.go
  wctl/ws_stake.go
Labels: enhancement

#402 Check block height of all transactions listed under a queried block, and cleanup vote methods and don't allow NewBlock() to return errors.
  accounts_test.go
  block.go
  block_test.go
  blocks_test.go
  collapse_test.go
  db.go
  genesis.go
  ledger.go
  ledger_test.go
  log_test.go
  protocol.go
  testutil.go
  transactions_test.go
  tx_applier_test.go
  vote.go
  vote_test.go
Labels: bug

#405 Move debounce, filebuffer, stall detector into internal packages.
  api/mod.go
  api/ws.go
  cmd/wctl/payloads.md
  internal/cuckoo/filter.go
  internal/debounce/config.go
  internal/debounce/debounce.go
  internal/debounce/debounce_test.go
  internal/debounce/payload.go
  internal/filebuffer/pool.go
  internal/stall/detector.go
  internal/stall/detector_unix.go
  internal/stall/detector_windows.go
  ledger.go
Labels: enhancement

#406 Cleanup modules, simplify state collapse caching, and make certain marshal methods zero-alloc.
  avl/lru.node.go
  avl/tree.go
  block.go
  collapse.go
  common.go
  contract.go
  internal/radix/index.go
  ledger.go
  lru.state.go
  lru.vm.go
  lru/lru.go
  lru/lru_test.go
  protocol.go
  vote.go
  vote_test.go
Labels: enhancement

#408 Provide AVX2-optimized instructions and other tricks to speed up decoding Cuckoo filters.
  go.mod
  go.sum
  internal/cuckoo/asm/asm.go
  internal/cuckoo/count.go
  internal/cuckoo/count_amd64.go
  internal/cuckoo/count_amd64.s
  internal/cuckoo/filter.go
  internal/cuckoo/filter_test.go
  protocol.go
Labels: enhancement

#409 Remove duplicated dump entry in help, and add alias
  cmd/wavelet/cli.go
Labels: bug

#407 ledger: check that transaction ids in a block are properly sorted
  ledger.go
  transactions.go
  transactions_test.go
  tx.go
  tx_test.go
Labels: bug, enhancement

#390 Github CI improvements.
  .github/workflows/workflow.yml
Labels: devops, enhancement

#410 Fix order in which collapseTransactions gets called to produce block ID, logical data races, and adapt a new BTree package.
  block_test.go
  collapse.go
  collapse_test.go
  go.mod
  go.sum
  internal/btree/btree.go
  internal/btree/btree_test.go
  ledger.go
  log_test.go
  transactions.go
  transactions_test.go
  tx_test.go
Labels: bug

#389 Fix failing genesis tests
  genesis_integration_test.go
Labels: devops

#413 vote: normalize individual weights before passing through Normalize()
  vote.go
Labels: bug

#414 Fix batch transaction signature validation
  tx_validate.go
  tx_validate_test.go
Labels: bug

#418 Fix syncing contract transaction.
  ledger.go
  protocol.go
  tx_validate.go
Labels: bug

#420 fix(Docker): Add git version to docker build
  Dockerfile
  Makefile
Labels: devops

#419 Keep track of finalized transaction IDs in ledger state to prevent double spending upon state syncing, improve overall security of state syncing, cleanup state syncing code, and speed up transaction syncing.
  api/mod_ws_integration_test.go
  api/msg.go
  avl/tree.go
  blocks.go
  blocks_test.go
  collapse.go
  db.go
  db_test.go
  genesis.go
  genesis_integration_test.go
  internal/backoff/backoff.go
  internal/backoff/backoff_test.go
  ledger.go
  ledger_integration_test.go
  log.go
  log/io.go
  log/mod.go
  log_test.go
  protocol.go
  rpc.pb.go
  rpc.proto
  sync.go
  testutil.go
  transactions.go
Labels: bug, enhancement

#415 Re-propose a block if sampling stalls.
  snowball.go
  sync.go
Labels: enhancement

#425 Fix memory leak in arena allocation in API, temporarily remove API message debouncing, and speed up logging state changes.
  api/mod.go
  api/ws.go
  collapse.go
  ledger.go
  wctl/ws.go
  wctl/ws_accounts.go
Labels: enhancement

#426 ledger: allow FinalizeBlocks to gracefully stop
  ledger.go
Labels: bug

#427 api: fix tests and prevent stale fastjson.Value living longer than fastjson.Parser from pool in (*Gateway).Write
  api/mod.go
  api/mod_integration_test.go
  api/mod_ws_integration_test.go
Labels: bug

#424 Refactor integration tests.
  Makefile
  api/mod_integration_test.go
  avl/node_test.go
  avl/tree_test.go
  benchmarks/accounts.go
  benchmarks/tree.go
  cmd/wavelet/main_integration_test.go
  db_test.go
  genesis.go
  genesis_integration_test.go
  ledger.go
  ledger_integration_test.go
  ledger_test.go
  log_test.go
  store/testutil.go
  testutil.go
  tx_applier.go
  tx_validate.go
  utils_test.go
Labels: bug, enhancement

#428 ledger: force nodes to sample themselves
  dbg.go
  dbg_noop.go
  ledger.go
  snowball.go
Labels: enhancement

#432 Add second to log timestamp format
  log/console.go
Labels: enhancement

#434 Add log.nocolor flag to disable color in logs
  cmd/wavelet/cli.go
  cmd/wavelet/main.go
  log/console.go
Labels: enhancement
